name: effectiveness_of_incentives
channels:
  - pytask
  - conda-forge

dependencies:
  - conda-build
  - econtools>=0.3.2
  - ipykernel
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pytask>=0.0.11
  - pytask-latex>=0.0.10


  - pytest
  - pytest-cov
  - python=3.8.5
  - python-graphviz
  - scipy>=1.6.1
  - patsy>=0.5.1
  - seaborn
  - statsmodels>=0.12.2


  - virtualenv=20.0.33

  - pip:

    - pre-commit

    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex

